// Screen Titles
const VERIFICATION_SCREEN_TITLE = "Verify Your Account";
const SELECT_BILLING_ADDRESS_SCREEN_TITLE = "Billing Address";
const SEARCH_SUGGESTION_SCREEN_TITLE = "Search Page";
const HOME_SCREEN_TITLE = "Home";
const PRODUCT_DETAIL_SCREEN_TITLE = "About the Product";
const CART_SCREEN_TITLE = "Cart";
const SAVED_ITEMS_SCREEN_TITLE = "Saved Items";
const SIGN_IN_SCREEN_TITLE = "Sign In";
const SIGN_UP_SCREEN_TITLE = "Sign Up";
const FORGOT_PASSWORD_SCREEN_TITLE = "Forgot Password";
const CHANGE_PASSWORD_SCREEN_TITLE = "Change Password";
const USER_PROFILE_SCREEN_TITLE = "User Profile";
const ADMIN_PROFILE_SCREEN_TITLE = "Admin Profile";
const ORDER_HISTORY_SCREEN_TITLE = "Order History";
const NOTIFICATIONS_SCREEN_TITLE = "Notifications Settings";
const CUSTOMER_SUPPORT_SCREEN_TITLE = "Customer Support";
const SEARCH_SCREEN_TITLE = "Search";
const ADMIN_CATEGORIES_SCREEN_TITLE = "Categories";
const ADD_ADDRESS_SCREEN_TITLE = "Add New Address";
const UPDATE_ADDRESS_SCREEN_TITLE = "Update Address";
const ADD_BILLING_ADDRESS_SCREEN_TITLE = "Add Billing Address";
const UPDATE_BILLING_ADDRESS_SCREEN_TITLE = "EDIT Billing Address";
const ADMIN_ORDER_DETAIL_SCREEN_TITLE = "Order Detail";
const ADMIN_ORDER_QR_SCREEN_TITLE = "Scan QR Code";
const ADMIN_PRODUCT_DASHBOARD_SCREEN_TITLE = "Product Details";
const ADMIN_PRODUCT_UPDATE_SCREEN_TITLE = "Update Product";
const ADMIN_PRODUCT_ADD_SCREEN_TITLE = "Add Product";
const ADMIN_SEE_ALL_ORDERS_SCREEN_TITLE = "See All Orders";
const ADMIN_ACCESS_CONTROL_SCREEN_TITLE = "User Access Control";
const APP_REVIEW_SCREEN_TITLE = "Feedback";
const CANCEL_ORDER_SCREEN_TITLE = "Cancel Order";
const DELIVERY_TRACKING_SCREEN_TITLE = "Order Tracking";
const EDIT_ACCOUNT_INFORMATION_SCREEN_TITLE = "Edit Contact Information";
const EDIT_ADDRESS_SCREEN_TITLE = "Edit Address";
const EDIT_PROFILE_SCREEN_TITLE = "Edit Profile";
const FILTER_SCREEN_TITLE = "Filters";
const HOME_DELIVERY_SCREEN_TITLE = "Home Delivery";
const MY_ORDERS_SCREEN_TITLE = "Your Orders";
const NOTIFICATIONS_LISTING_SCREEN_TITLE = "Notifications";
const ORDER_SUMMARY_SCREEN_TITLE = "Order Summary";
const PICKUP_MODE_SCREEN_TITLE = "Pickup Options";
const REVIEW_SCREEN_TITLE = "Product Reviews";
const SAVED_ADDRESS_SCREEN_TITLE = "Saved Address";
const FEEDBACK_SCREEN2_TITLE = "Add Your Review";
const FILE_UPLOAD = "File Upload";
const STORE_OFFERS = "Store Offers";

// Delivery Modes
const DELIVERY_MODE_HOME = "Home Delivery";
const DELIVERY_MODE_STORE = "Store Pickup";
const DELIVERY_MODE_CURBSIDE = "Curbside Pickup";

//OrderPlacedMessages
const ORDER_PLACED_SUCCESS = "Your order has been placed successfully";
const ORDER_PLACED_FAILED = "Your order has been failed to place";

//Footer
const FOOTER_HOME = "home";
const FOOTER_CART = "cart";
const FOOTER_MENU = "menu";
const FOOTER_SAVED = "saved";
const FOOTER_SEARCH = "search";

//ADMIN FOOTER
const ADMINFOOTER_HOME = "home";
const ADMINFOOTER_CATEGORIES = "categories";
const ADMINFOOTER_ORDERS = "orders";
const ADMINFOOTER_PRODUCTS = "products";
const ADMINFOOTER_SCAN = "scan&deliver";

//DEFAULT_PICKUP_HOURS
const DEFAULT_PICKUP_HOURS = 2;

//Store timings
const STORE_OPENING_TIMINGS = 7;
const STORE_CLOSING_TIMINGS = 17;

//Minimum UserAge
const MINIMUM_USER_AGE = 12;

//Date Formats
const DATE_FORMAT_Display = "dd/MM/yyyy";
const DATE_FORMAT_API = "YYYY-MM-DDTHH:mm:ss.sssZ";

// Export all constants
export {
  DATE_FORMAT_Display,
  DATE_FORMAT_API,
  MINIMUM_USER_AGE,
  FILE_UPLOAD,
  ADMIN_PRODUCT_ADD_SCREEN_TITLE,
  STORE_OPENING_TIMINGS,
  STORE_CLOSING_TIMINGS,
  DEFAULT_PICKUP_HOURS,
  ADMINFOOTER_CATEGORIES,
  ADMINFOOTER_HOME,
  ADMINFOOTER_ORDERS,
  ADMINFOOTER_PRODUCTS,
  ADMINFOOTER_SCAN,
  DELIVERY_MODE_CURBSIDE,
  FOOTER_HOME,
  FOOTER_CART,
  FOOTER_MENU,
  FOOTER_SAVED,
  FOOTER_SEARCH,
  ORDER_PLACED_FAILED,
  ORDER_PLACED_SUCCESS,
  FEEDBACK_SCREEN2_TITLE,
  VERIFICATION_SCREEN_TITLE,
  SELECT_BILLING_ADDRESS_SCREEN_TITLE,
  SEARCH_SUGGESTION_SCREEN_TITLE,
  HOME_SCREEN_TITLE,
  PRODUCT_DETAIL_SCREEN_TITLE,
  CART_SCREEN_TITLE,
  SAVED_ITEMS_SCREEN_TITLE,
  SIGN_IN_SCREEN_TITLE,
  SIGN_UP_SCREEN_TITLE,
  FORGOT_PASSWORD_SCREEN_TITLE,
  CHANGE_PASSWORD_SCREEN_TITLE,
  USER_PROFILE_SCREEN_TITLE,
  ADMIN_PROFILE_SCREEN_TITLE,
  ORDER_HISTORY_SCREEN_TITLE,
  NOTIFICATIONS_SCREEN_TITLE,
  CUSTOMER_SUPPORT_SCREEN_TITLE,
  SEARCH_SCREEN_TITLE,
  ADMIN_CATEGORIES_SCREEN_TITLE,
  ADD_ADDRESS_SCREEN_TITLE,
  UPDATE_ADDRESS_SCREEN_TITLE,
  ADD_BILLING_ADDRESS_SCREEN_TITLE,
  UPDATE_BILLING_ADDRESS_SCREEN_TITLE,
  ADMIN_ORDER_DETAIL_SCREEN_TITLE,
  ADMIN_ORDER_QR_SCREEN_TITLE,
  ADMIN_PRODUCT_DASHBOARD_SCREEN_TITLE,
  ADMIN_PRODUCT_UPDATE_SCREEN_TITLE,
  ADMIN_SEE_ALL_ORDERS_SCREEN_TITLE,
  ADMIN_ACCESS_CONTROL_SCREEN_TITLE,
  APP_REVIEW_SCREEN_TITLE,
  CANCEL_ORDER_SCREEN_TITLE,
  DELIVERY_TRACKING_SCREEN_TITLE,
  EDIT_ACCOUNT_INFORMATION_SCREEN_TITLE,
  EDIT_ADDRESS_SCREEN_TITLE,
  EDIT_PROFILE_SCREEN_TITLE,
  FILTER_SCREEN_TITLE,
  HOME_DELIVERY_SCREEN_TITLE,
  MY_ORDERS_SCREEN_TITLE,
  NOTIFICATIONS_LISTING_SCREEN_TITLE,
  ORDER_SUMMARY_SCREEN_TITLE,
  PICKUP_MODE_SCREEN_TITLE,
  REVIEW_SCREEN_TITLE,
  SAVED_ADDRESS_SCREEN_TITLE,
  DELIVERY_MODE_HOME,
  DELIVERY_MODE_STORE,
  STORE_OFFERS,
};
