trigger:
  branches:
    include:
      - main
      - develop
      - feature/ci-cd

pool:
  vmImage: 'ubuntu-latest'

variables:
  - name: NODE_VERSION
    value: '18.x'

stages:
- stage: Build
  jobs:
  - job: BuildApp
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: $(NODE_VERSION)
      displayName: 'Install Node.js'

    - script: |
        npm install -g eas-cli
        npm install
      displayName: 'Install dependencies'

    - task: DownloadSecureFile@1
      name: keystoreFile
      inputs:
        secureFile: 'my-upload-key.keystore'
      displayName: 'Download Keystore file'

    - script: |
        mkdir -p android/app
        cp $(keystoreFile.secureFilePath) android/app/my-upload-key.keystore
        chmod +x android/app/my-upload-key.keystore
      displayName: 'Copy keystore'

    # Create credentials.json
    - script: |
        echo '{
          "android": {
            "keystore": {
              "keystorePath": "android/app/my-upload-key.keystore",
              "keystorePassword": "$(ANDROID_KEYSTORE_PASSWORD)",
              "keyAlias": "$(ANDROID_KEY_ALIAS)",
              "keyPassword": "$(ANDROID_KEY_PASSWORD)"
            }
          }
        }' > credentials.json
      displayName: 'Create credentials.json'

    # Create environment file
    - script: |
        touch .env
        echo "EXPO_TOKEN=$(EXPO_TOKEN)" >> .env
      displayName: 'Create environment file'

    # Verify Expo login
    - script: |
        export EXPO_TOKEN=$(EXPO_TOKEN)
        npx eas whoami
      displayName: 'Verify Expo login'
      env:
        EXPO_TOKEN: $(EXPO_TOKEN)

    # Build AAB (Internal Testing) for feature/ci-cd branch
    - script: |
        export EXPO_TOKEN=$(EXPO_TOKEN)
        yes | eas build --platform android --profile preview --non-interactive --no-wait
      displayName: 'Build Android App Bundle for Internal Testing'
      condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/feature/ci-cd'))
      env:
        EXPO_TOKEN: $(EXPO_TOKEN)

    # Build AAB (Internal Testing) for develop branch
    - script: |
        export EXPO_TOKEN=$(EXPO_TOKEN)
        yes | eas build --platform android --profile preview --non-interactive --no-wait
      displayName: 'Build Android App Bundle for Internal Testing'
      condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/develop'))
      env:
        EXPO_TOKEN: $(EXPO_TOKEN)

    # Build APK (Production) for main branch
    - script: |
        export EXPO_TOKEN=$(EXPO_TOKEN)
        yes | eas build --platform android --profile production --non-interactive --no-wait
      displayName: 'Build Android APK for Production'
      condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
      env:
        EXPO_TOKEN: $(EXPO_TOKEN)
