export default {homeScreen: "home/home",
  searchScreen: "search/search",
  productDetailScreenScreen: "productDetailScreen/productDetailScreen",
  searchSuggesionsScreenScreen: "searchSuggesionsScreen/searchSuggesionsScreen",
  searchResultsScreenScreen: "searchResultsScreen/searchResultsScreen",
  welcomeScreen: "welcome/welcome",
  signInScreen: "signIn/signIn",
  catagoryScreenScreen: "catagoryScreen/catagoryScreen",
  reviewsScreenScreen: "reviewsScreen/reviewsScreen",
  userReviewScreenScreen: "userReviewScreen/userReviewScreen",
  cartScreenScreen: "cartScreen/cartScreen",
  pickupScreenScreen: "pickupScreen/pickupScreen",
  pickUpModescreenScreen: "pickUpModescreen/pickUpModescreen",
  storePickUpScreenScreen: "storePickUpScreen/storePickUpScreen",
  curbsidePickupScreenScreen: "curbsidePickupScreen/curbsidePickupScreen",
  homeDeliveryScreenScreen: "homeDeliveryScreen/homeDeliveryScreen",
  orderSummeryScreenScreen: "orderSummeryScreen/orderSummeryScreen",
  paymentScreenScreen: "paymentScreen/paymentScreen",
  paymentSaveCardScreenScreen: "paymentSaveCardScreen/paymentSaveCardScreen",
  billingAddressScreenScreen: "addBillingAddressScreen/addBillingAddressScreen",
  orderSuccessfulScreenScreen: "orderSuccessfulScreen/orderSuccessfulScreen",
  deliveryTrackingScreenScreen: "deliveryTrackingScreen/deliveryTrackingScreen",
  offersScreenScreen: "offersScreen/offersScreen",
  splashScreenScreen: "splashScreen/splashScreen",
  welcomeScreenScreen: "welcomeScreen/welcomeScreen",
  signUpScreenScreen: "signUpScreen/signUpScreen",
  mailVerificationScreenScreen: "mailVerificationScreen/mailVerificationScreen",
  resedMailScreenScreen: "resedMailScreen/resedMailScreen",
  verifcationScreenScreen: "verifcationScreen/verifcationScreen",
  passwordResetScreenScreen: "passwordResetScreen/passwordResetScreen",
  verifyUserScreenScreen: "verifyUserScreen/verifyUserScreen",
  forgotPasswordScreenScreen: "forgotPasswordScreen/forgotPasswordScreen",
  userProfileScreenScreen: "userProfileScreen/userProfileScreen",
  editProfileScreenScreen: "editProfileScreen/editProfileScreen",
  editAccountInformationscreenScreen:
    "editAccountInformationscreen/editAccountInformationscreen",
  changePasswordScreenScreen: "changePasswordScreen/changePasswordScreen",
  notificationsScreenScreen: "notificationsScreen/notificationsScreen",
  customerSupportScreenScreen: "customerSupportScreen/customerSupportScreen",
  myOrderScreenScreen: "myOrderScreen/myOrderScreen",
  orderDetailsScreenScreen: "orderDetailsScreen/orderDetailsScreen",
  savedItemScreenScreen: "savedItemScreen/savedItemScreen",
  savedAddressScreenScreen: "savedAddressScreen/savedAddressScreen",
  editAddressScreenScreen: "editAddressScreen/editAddressScreen",
  allPaymentsScreenScreen: "allPaymentsScreen/allPaymentsScreen",
  updateCardDetailsScreenScreen:
    "updateCardDetailsScreen/updateCardDetailsScreen",
  addNewPaymentScreenScreen: "addNewPaymentScreen/addNewPaymentScreen",
  feedBackScreenScreen: "feedBackScreen/feedBackScreen",
  dashBoardScreenScreen: "dashBoardScreen/dashBoardScreen",
  filterScreen: "filter/filter",
  categoriesScreeScreen: "categoriesScree/categoriesScree",
  AdminDashboardScreen: "AdminDashboard/AdminDashboard",
  AdminSeeAllOrdersScreen: "AdminSeeAllOrders/AdminSeeAllOrders",
  AdminOrderDetailScreen: "AdminOrderDetail/AdminOrderDetail",
  AdminProductDashboardScreen: "AdminProductDashboard/AdminProductDashboard",
  AdminProductUpdationScreen: "AdminProductUpdation/AdminProductUpdation",
  AdminStoreInformationScreen: "AdminStoreInformation/AdminStoreInformation",
  AdminOrderQRScanScreen: "AdminOrderQRScan/AdminOrderQRScan",
  NotificationListingScreen: "NotificationListing/NotificationListing",
  returnOrderScreen: "returnOrder/returnOrder",
  AppReviewScreenScreen: "AppReviewScreen/AppReviewScreen",
  cancelOrderScreen: "cancelOrder/cancelOrder",
  replaceOrderScreenScreen: "replaceOrderScreen/replaceOrderScreen",
  addAddressScreenScreen: "addAddressScreen/addAddressScreen",
  selectBillingAddressScreenScreen:"selectBillingAddressScreen/selectBillingAddressScreen",
  AdminCategoriesScreen: 'AdminCategories/AdminCategories', 
  UserNotificationsScreen: 'UserNotifications/UserNotifications', biometricSettingsScreen: 'biometricSettings/biometricSettings'};
