export default {
  primary: "#17C6ED",
  lightgrey: "#F8F8F8",
  placeholderTextColor: "#D0CBFD",
  black: "#040404",
  white: "#fff",
  starColor: "#FBBC05",
  reviewsColor: "#6E6F76",
  lightSkyBlue: "#E9F3F6",
  secondary: "#CEF1F9",
  secondaryText: "#7E8A8C",
  switchTrackOff: "#D2D3D8",
  error: "red",
  placeholdergrey: "#D9D9D9",
  buttonError: "#EB0A0A",
  lightGreen: "#DCF0E4",
};
