import { StyleSheet } from "react-native";
import colors from "../../../constants/colors";

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.white,
  },
  contentContainer: {
    flex: 1,
    paddingHorizontal: 16,
    paddingTop: 16,
    paddingBottom: 24,
  },
  contentContainerWeb: {
    width: "60%",
    alignSelf: "center",
    paddingTop: 24,
    paddingBottom: 32,
  },
  contentContainerMobileWeb: {
    width: "100%",
    maxWidth: 440,
    alignSelf: "center",
    paddingHorizontal: 12,
    paddingTop: 16,
    paddingBottom: 24,
  },
  card: {
    width: "100%",
  },
  cardWeb: {
    backgroundColor: colors.white,
    borderRadius: 16,
    padding: 24,
    borderWidth: 1,
    borderColor: colors.lightgrey,
    shadowColor: colors.black,
    shadowOpacity: 0.08,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 4 },
    elevation: 3,
  },
  cardMobileWeb: {
    width: "100%",
    maxWidth: "100%",
    padding: 20,
    borderRadius: 18,
  },
  headerRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 12,
    marginBottom: 18,
  },
  headerRowMobileWeb: {
    marginBottom: 16,
  },
  headerTextWrap: {
    flex: 1,
  },
  headerIconWrap: {
    width: 40,
    height: 40,
    borderRadius: 12,
    backgroundColor: colors.secondary,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: colors.lightgrey,
  },
  title: {
    fontSize: 20,
    fontWeight: "700",
    color: colors.black,
    marginBottom: 6,
  },
  titleMobileWeb: {
    fontSize: 18,
    lineHeight: 24,
  },
  subtitle: {
    fontSize: 13,
    color: colors.slateGrey,
    lineHeight: 18,
  },
  subtitleMobileWeb: {
    fontSize: 15,
    lineHeight: 22,
  },
  scanFrame: {
    borderWidth: 1,
    borderColor: colors.lightgrey,
    borderStyle: "dashed",
    borderRadius: 16,
    paddingVertical: 26,
    paddingHorizontal: 16,
    alignItems: "center",
    backgroundColor: colors.secondary,
  },
  scanFrameMobileWeb: {
    paddingVertical: 22,
    paddingHorizontal: 14,
  },
  scanIconCircle: {
    width: 96,
    height: 96,
    borderRadius: 48,
    backgroundColor: colors.white,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: colors.lightgrey,
    marginBottom: 10,
  },
  scanIconCircleMobileWeb: {
    width: 104,
    height: 104,
    borderRadius: 52,
  },
  scanHint: {
    fontSize: 13,
    fontWeight: "500",
    color: colors.secondaryText,
    textAlign: "center",
  },
  dividerRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    marginTop: 18,
    marginBottom: 14,
  },
  dividerLine: {
    flex: 1,
    height: 1,
    backgroundColor: colors.lightgrey,
  },
  dividerText: {
    fontSize: 12,
    fontWeight: "700",
    color: colors.slateGrey,
    letterSpacing: 0.6,
  },
  inputSection: {
    marginTop: 2,
    // paddingHorizontal: 16,
  },
  inputSectionMobileWeb: {
    marginTop: 6,
  },
  inputLabel: {
    fontSize: 14,
    color: colors.black,
    marginBottom: 6,
    fontWeight: "600",
  },
  verifyButton: {
    backgroundColor: colors.primary,
    paddingVertical: 14,
    borderRadius: 12,
    marginTop: 20,
    alignItems: "center",
  },
  verifyButtonMobileWeb: {
    marginTop: 18,
    borderRadius: 14,
  },
  buttonText: {
    color: colors.white,
    fontWeight: "600",
    fontSize: 16,
  },
});
