import { StyleSheet } from "react-native";
import colors from "../../../constants/colors";

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.offWhite,
  },
  mobileContent: {
    paddingHorizontal: 16,
    paddingTop: 16,
    paddingBottom: 32,
  },
  mobileCartItem: {
    paddingHorizontal: 0,
  },
  mobileHeroCard: {
    backgroundColor: colors.white,
    borderRadius: 22,
    padding: 20,
    borderWidth: 1,
    borderColor: colors.lightgrey,
    marginBottom: 16,
  },
  mobileEyebrow: {
    fontSize: 12,
    fontWeight: "700",
    letterSpacing: 1,
    textTransform: "uppercase",
    color: colors.primary,
    marginBottom: 10,
  },
  mobileHeroTitle: {
    fontSize: 28,
    fontWeight: "700",
    color: colors.black,
    marginBottom: 8,
  },
  mobileHeroSubtitle: {
    fontSize: 14,
    lineHeight: 22,
    color: colors.slateGrey,
    marginBottom: 16,
  },
  mobileStatGrid: {
    gap: 10,
  },
  mobileStatTile: {
    backgroundColor: colors.secondary,
    borderRadius: 16,
    paddingVertical: 12,
    paddingHorizontal: 14,
  },
  mobileStatLabel: {
    fontSize: 11,
    fontWeight: "700",
    letterSpacing: 0.8,
    textTransform: "uppercase",
    color: colors.slateGrey,
    marginBottom: 6,
  },
  mobileStatValue: {
    fontSize: 16,
    fontWeight: "700",
    color: colors.black,
  },
  mobileSectionCard: {
    backgroundColor: colors.white,
    borderRadius: 22,
    padding: 18,
    borderWidth: 1,
    borderColor: colors.lightgrey,
    marginBottom: 16,
  },
  mobileSectionTitle: {
    fontSize: 20,
    fontWeight: "700",
    color: colors.black,
    marginBottom: 14,
  },
  mobileValueText: {
    fontSize: 16,
    lineHeight: 24,
    color: colors.black,
  },
  mobileDetailRow: {
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: colors.lightgrey,
  },
  mobileDetailLabel: {
    fontSize: 12,
    fontWeight: "700",
    letterSpacing: 0.8,
    textTransform: "uppercase",
    color: colors.slateGrey,
    marginBottom: 4,
  },
  mobileDetailValue: {
    fontSize: 15,
    lineHeight: 22,
    color: colors.black,
    fontWeight: "600",
  },
  mobileTimelineWrap: {
    minHeight: 0,
    paddingTop: 4,
  },
  mobileFieldLabel: {
    fontSize: 12,
    fontWeight: "700",
    letterSpacing: 0.8,
    textTransform: "uppercase",
    color: colors.slateGrey,
    marginBottom: 8,
  },
  mobileDropdown: {
    borderWidth: 1,
    borderColor: colors.lightgrey,
    borderRadius: 14,
    backgroundColor: colors.white,
    minHeight: 52,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 14,
  },
  mobileDropdownText: {
    fontSize: 16,
    color: colors.black,
    flex: 1,
    fontWeight: "600",
  },
  mobileReasonWrap: {
    marginTop: 16,
  },
  mobileReasonRequired: {
    color: colors.error,
    fontSize: 14,
  },
  mobileReasonInput: {
    minHeight: 108,
  },
  mobileButtonWrap: {
    marginTop: 20,
    marginBottom: 40,
  },
  mobileButton: {
    borderRadius: 14,
    paddingVertical: 16,
  },
  webPage: {
    flex: 1,
    backgroundColor: colors.offWhite,
  },
  webShell: {
    width: "100%",
    maxWidth: 1280,
    alignSelf: "center",
    paddingHorizontal: 24,
    paddingTop: 24,
    paddingBottom: 40,
  },
  webShellMobile: {
    paddingHorizontal: 12,
    paddingTop: 16,
  },
  webTopRow: {
    flexDirection: "row",
    gap: 20,
    marginBottom: 20,
    alignItems: "stretch",
  },
  webTopRowMobile: {
    flexDirection: "column",
  },
  webHeroCard: {
    flex: 1.5,
    backgroundColor: colors.white,
    borderRadius: 24,
    padding: 28,
    borderWidth: 1,
    borderColor: colors.lightgrey,
    shadowColor: colors.black,
    shadowOpacity: 0.06,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 6 },
    elevation: 3,
  },
  webHeroCardMobile: {
    flex: undefined,
    width: "100%",
    padding: 18,
    borderRadius: 20,
  },
  webDetailsCard: {
    flex: 1,
    backgroundColor: colors.white,
    borderRadius: 24,
    padding: 24,
    borderWidth: 1,
    borderColor: colors.lightgrey,
    shadowColor: colors.black,
    shadowOpacity: 0.06,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 6 },
    elevation: 3,
  },
  webDetailsCardMobile: {
    flex: undefined,
    width: "100%",
    padding: 18,
    borderRadius: 20,
  },
  webEyebrow: {
    fontSize: 12,
    fontWeight: "700",
    letterSpacing: 1.2,
    textTransform: "uppercase",
    color: colors.primary,
    marginBottom: 10,
  },
  webTitle: {
    fontSize: 34,
    fontWeight: "700",
    color: colors.black,
    marginBottom: 10,
  },
  webTitleMobile: {
    fontSize: 24,
    lineHeight: 30,
  },
  webSubtitle: {
    fontSize: 15,
    lineHeight: 24,
    color: colors.slateGrey,
    marginBottom: 22,
    maxWidth: 640,
  },
  webSubtitleMobile: {
    fontSize: 14,
    lineHeight: 22,
    marginBottom: 16,
  },
  webSummaryGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 14,
  },
  webSummaryGridMobile: {
    flexDirection: "column",
    gap: 10,
  },
  webSummaryTile: {
    minWidth: 170,
    flexGrow: 1,
    backgroundColor: colors.secondary,
    borderRadius: 18,
    paddingVertical: 16,
    paddingHorizontal: 18,
  },
  webSummaryTileMobile: {
    minWidth: 0,
    width: "100%",
    paddingVertical: 8,
    paddingHorizontal: 10,
    borderRadius: 12,
  },
  webSummaryLabel: {
    fontSize: 12,
    fontWeight: "700",
    textTransform: "uppercase",
    letterSpacing: 0.8,
    color: colors.slateGrey,
    marginBottom: 8,
  },
  webSummaryValue: {
    fontSize: 18,
    fontWeight: "700",
    color: colors.black,
  },
  webSummaryValueMobile: {
    fontSize: 15,
    lineHeight: 18,
  },
  webCardTitle: {
    fontSize: 22,
    fontWeight: "700",
    color: colors.black,
    marginBottom: 12,
  },
  webDetailRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    gap: 12,
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: colors.lightgrey,
  },
  webDetailLabel: {
    fontSize: 13,
    fontWeight: "700",
    color: colors.slateGrey,
    textTransform: "uppercase",
    letterSpacing: 0.6,
  },
  webDetailValue: {
    flex: 1,
    textAlign: "right",
    fontSize: 15,
    fontWeight: "600",
    color: colors.black,
  },
  webAddressBlock: {
    marginTop: 16,
    backgroundColor: colors.secondary,
    borderRadius: 18,
    padding: 16,
  },
  webAddressValue: {
    marginTop: 8,
    fontSize: 15,
    lineHeight: 24,
    color: colors.black,
  },
  webMainGrid: {
    flexDirection: "row",
    gap: 20,
    alignItems: "flex-start",
  },
  webMainGridMobile: {
    flexDirection: "column",
    gap: 16,
  },
  webProductsCard: {
    flex: 1.4,
    backgroundColor: colors.white,
    borderRadius: 24,
    padding: 24,
    borderWidth: 1,
    borderColor: colors.lightgrey,
    shadowColor: colors.black,
    shadowOpacity: 0.06,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 6 },
    elevation: 3,
  },
  webProductsCardMobile: {
    flexGrow: 0,
    flexShrink: 1,
    flexBasis: "auto",
    width: "100%",
    padding: 18,
    borderRadius: 20,
    minHeight: 0,
    shadowColor: colors.black,
    shadowOpacity: 0.06,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 4 },
    elevation: 2,
  },
  webSideColumn: {
    flex: 1,
    gap: 20,
  },
  webSideColumnMobile: {
    width: "100%",
  },
  webSectionHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 16,
  },
  webSectionMeta: {
    fontSize: 13,
    fontWeight: "700",
    color: colors.slateGrey,
    textTransform: "uppercase",
    letterSpacing: 0.8,
  },
  webCartItem: {
    paddingHorizontal: 0,
  },
  webTimelineCard: {
    backgroundColor: colors.white,
    borderRadius: 24,
    padding: 24,
    borderWidth: 1,
    borderColor: colors.lightgrey,
    shadowColor: colors.black,
    shadowOpacity: 0.06,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 6 },
    elevation: 3,
  },
  webTimelineCardMobile: {
    width: "100%",
    padding: 18,
    borderRadius: 20,
  },
  webTimelineSubtitle: {
    fontSize: 14,
    lineHeight: 22,
    color: colors.slateGrey,
    marginBottom: 12,
  },
  webTimelineWrap: {
    paddingTop: 4,
  },
  webTimelineWrapMobile: {
    minHeight: 0,
    paddingTop: 0,
  },
  webStatusCard: {
    backgroundColor: colors.white,
    borderRadius: 24,
    padding: 24,
    borderWidth: 1,
    borderColor: colors.lightgrey,
    shadowColor: colors.black,
    shadowOpacity: 0.06,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 6 },
    elevation: 3,
  },
  webStatusCardMobile: {
    width: "100%",
    padding: 18,
    borderRadius: 20,
  },
  webStatusHelp: {
    fontSize: 14,
    lineHeight: 22,
    color: colors.slateGrey,
    marginBottom: 16,
  },
  webFieldLabel: {
    fontSize: 13,
    fontWeight: "700",
    color: colors.slateGrey,
    textTransform: "uppercase",
    letterSpacing: 0.6,
    marginBottom: 8,
  },
  webDropdown: {
    borderWidth: 1,
    borderColor: colors.lightgrey,
    borderRadius: 14,
    backgroundColor: colors.white,
    minHeight: 52,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 14,
  },
  webDropdownText: {
    fontSize: 16,
    color: colors.black,
    flex: 1,
    fontWeight: "600",
  },
  webReasonWrap: {
    marginTop: 16,
  },
  webReasonInput: {
    minHeight: 108,
  },
  webButtonRow: {
    marginTop: 20,
  },
  webPrimaryButton: {
    borderRadius: 14,
    paddingVertical: 16,
  },
  webMobileItemCard: {
    flexDirection: "row",
    alignItems: "stretch",
    backgroundColor: colors.white,
    borderRadius: 18,
    overflow: "hidden",
    marginBottom: 12,
    borderWidth: 1,
    borderColor: colors.lightgrey,
    shadowColor: colors.black,
    shadowOpacity: 0.05,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 3 },
    elevation: 2,
  },
  webMobileItemImageWrap: {
    width: 110,
    height: 96,
    backgroundColor: colors.lightgrey,
  },
  webMobileItemImage: {
    width: "100%",
    height: "100%",
    resizeMode: "cover",
  },
  webMobileItemContent: {
    flex: 1,
    flexBasis: 0,
    minWidth: 0,
    maxWidth: "100%",
    overflow: "hidden",
    paddingHorizontal: 12,
    paddingVertical: 12,
    justifyContent: "center",
  },
  webMobileItemName: {
    fontSize: 15,
    fontWeight: "700",
    color: colors.black,
    marginBottom: 6,
    width: "100%",
    maxWidth: "100%",
    flexShrink: 1,
    flexWrap: "wrap",
    overflow: "hidden",
    lineHeight: 20,
  },
  webMobileItemMeta: {
    fontSize: 15,
    fontWeight: "600",
    color: colors.black,
    marginBottom: 6,
  },
  webMobileItemPrice: {
    fontSize: 17,
    fontWeight: "700",
    color: colors.primary,
  },
  text: {
    fontSize: 12,
    color: "black",
  },
  addressText: {
    fontSize: 15,
  },
});

export default styles;
